export const specialities = [
    "General Practice",
    "Allergy Medicine",
    "Audiological Medicine",
    "Acute Medicine",
    "Clinical Genetics",
    "Clinical Neurophysiology",
    "Cardiology",
    "Clinical Pharmacology",
    "Dermatology",
    "Endocrinology and Diabetes",
    "Gastroenterology",
    "General Internal Medicine",
    "Genito-Urinary Medicine",
    "Geriatric Medicine",
    "Infectious Diseases",
    "Intensive Care Medicine",
    "Medical Oncology",
    "Medical Ophthalmology",
    "Neurology",
    "Occupational Medicine",
    "Palliative Medicine",
    "Pharmaceutical medicine",
    "Rehabilitation medicine",
    "Renal medicine - Nephrology",
    "Respiratory medicine",
    "Rheumatology",
    "Sport and Exercise Medicine",
    "Obstetrics and Gynaecology",
    "Ophthalmology - Eye surgery",
    "Paediatrics",
    "Child Health",
    "Pathology",
    "Chemical Pathology",
    "Haematology",
    "Histopathology",
    "Microbiology and Virology",
    "Psychiatry",
    "Child Psychiatry",
    "Forensic Psychiatry",
    "General Adult Psychiatry",
    "Old Age Psychiatry",
    "Psychiatry of Learning Disability",
    "Psychotherapy",
    "Public Health",
    "Radiology",
    "Clinical Radiology",
    "Interventional Radiology",
    "Nuclear Medicine",
    "Cardiothoracic Surgery",
    "General Surgery Neurosurgery",
    "Oral and Maxillofacial Surgery",
    "Otolaryngology - Ear Nose Throat",
    "Paediatric Surgery",
    "Plastic Surgery",
    "Trauma and Orthopaedic Surgery",
    "Urology - Renal or Kidney Surgery",
    "Clinical Oncology",
];

export const countries = [
    'Argentina',
    'Australia',
    'Australia',
    'Austria',
    'Belarus Samoa',
    'Belgium',
    'Bosnia Herzegovina',
    'Brazil',
    'Bulgaria',
    'Canada',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech',
    'Denmark',
    'Egypt',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hong Kong  ',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Ireland',
    'Israel',
    'Italy',
    'Jordan',
    'Kenya',
    'Latvia',
    'Lebanon',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malaysia',
    'Malta',
    'Mexico',
    'Monaco',
    'Netherlands',
    'New Zealand',
    'Norway',
    'Pakistan',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'San Marino',
    'Saudi Arabia',
    'serbia',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'South Afrika',
    'Spain',
    'Sri Lanka',
    'Sweden',
    'Switzerland',
    'Tunis',
    'Turkey',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
];

export const salutations = [
    'Mr',
    'Mrs',
    'Mr & Mrs',
    'Ms',
    'Miss',
    'Sir',
    'Rev',
    'Dr',
    'Ven',
    'Father',
    'Prof.',
    'Dame',
    'Lord',
    'Lady'
];

export const genders = [
    'Male',
    'Female',
    'Undisclosed'
]

export const organizations = [
    "GP Practice Doctor",
    "Clinical Pharmacist",
    "Advance Paramedic",
    "Volunteers",
    "Secondary Care",
    "Acute Response Team (ART)",
    "Complex ART",
    "Home Visiting Service"
    , "Hospice", "Ambulance",
    "Community Menal Health Service",
    "District Nurses",
    "Speech and Language",
    "Community Optician and Audiologist",
    "Community Dentist",
    "Phsio and OT",
    "Social Services",
    "Private cares"
]

export const roles = Object.freeze({
    ADMIN: 'ADMIN',
    ROLE_ASSISTANT: 'ROLE_ASSISTANT',
    ROLE_PATIENT: 'ROLE_PATIENT',
    MEDICAL_SPECIALIST: 'MEDICAL_SPECIALIST'
})

export const routingRoles = Object.freeze({
    ADMIN: 'admin',
    ROLE_ASSISTANT: 'assistant',
    ROLE_PATIENT: 'patient',
    MEDICAL_SPECIALIST: 'doctor'
})
